language: c

before_install:
  - wget "https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.deb" -O dkp-pacman.deb
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - export PATH=${PATH}:${DEVKITARM}/bin

install:
  - sudo dpkg -i dkp-pacman.deb
  - sudo dkp-pacman -S --noconfirm devkitARM

script:
  - make
